### ISSUE TITLE
submit to Package Control

### ISSUE THREAD

**Issue by djsutherland** [NotSqrt/sublime-cython#1]
Putting this in Package Control would make it easier to use the package, so that users can do all their package management consistently / any updates can be pulled down automatically / etc.

[Steps to do so](https://sublime.wbond.net/docs/developers):
- Delete `package-metadata.json`, and set the github description field to the description that it contained.
- Fork the [Package Control Channel](https://github.com/wbond/package_control_channel) and add to `c.json` there:

``` json
{
    "name": "Cython",
    "details": "https://github.com/NotSqrt/sublime-cython",
    "releases": [
        {
            "details": "https://github.com/NotSqrt/sublime-cython/"
        }
    ]
}
```

This will make releases come from the master branch. Alternatively, you can tag releases and change the `details` url; details on this and other options [available here](https://raw.github.com/wbond/sublime_package_control/master/example-repository.json).
- Send a pull request with your change.

**Comment by NotSqrt** [comment]
Thanks ! Will do as soon as I can !

**Comment by NotSqrt** [comment]
Done !
